### ISSUE TITLE
References for list-style-images in core

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/purple#1]
If the theme is installed in root/themes the references in purple.css at lines 131 and 135 give a file not found report.
I think perhaps they should be
`
list-style-image:url(/core/misc/menu-collapsed.png);
`
and
`
list-style-image:url(/core/misc/menu-expanded.png);
`

**Comment by jenlampton** [comment]
Thanks @Graham-72 I have committed a fix for this issue :)
